use_frameworks!
platform :ios, '11.3'

pod 'WolfLua', :path => '../'

#pod 'WolfCore', :path => '../../WolfCore/'
# pod 'CLua', :path => '../../CLua'
pod 'CLua'

target 'WolfLua_Example' do
end

target 'WolfLua_Tests' do
end
